# Phase 1 Configuration
config:
  params:
    N: [256]
    d: [4, 6]
    eps: 1e-6
    moe-tensor-estimation:
      eps: 1e-6
    channel-gen:
      num-channels: 3
    first-pass:
      iters: 1000
      vecs: 100
      vec-survival: 0.1 # Top 10% of vectors survive
    second-pass:
      iters: 10000
      vec-survival: 0.1 # Top 1% of remaining vectors survive
      channel-survival: 0.2 # Top 20% of channels survive
    third-pass:
      iters: 500000
  output:
    output-directory: "results/phase11"



# Folder structure:
# results/
# └── phase1/
#     ├── channel1uid/
#     │   ├── first_pass/
#     │   │   ├── vec1/
#     │   │   ├── vec2/
#     │   │   ├── ...
#     │   │   └── vecs.json <-- contains vec parameters and results (eps entropy and estimated entropy) for each vec, as well as names
#     │   ├── second_pass/
#     │   │   ├── vec1/
#     │   │   ├── vec2/
#     │   │   ├── ...
#     │   │   └── vecs.json
#     │   ├── third_pass/ <-- only for the best surviving channels
#     │   │   ├── vec1/
#     │   │   ├── vec2/
#     │   │   ├── ...
#     │   │   └── vecs.json
#     │   ├── channel.json  <-- contains N, d, uid, tensor_entropy
#     │   └── kraus.dat
#     ├── channel2uid/
#     ├── ...
#     └── summary.json